version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: ekrem/chatbot-client:latest
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: kahraman42/chatbot-server:latest
    environment:
      - ENVIRONMENT=production
    ports:
      - "8000:8000"

